### ISSUE TITLE
Need ZenHub licenses

### ISSUE THREAD

**Issue by wayne-optin** [githubOptin/process-playground#3]
ZenHub is $5/user/month for what we need (private repos, etc). Probably assign licenses to Mark, Wayne, John, Dave, Dan at least.

https://www.zenhub.com/pricing

**Comment by optin-john** [comment]
@mfsmillie I don't have a zen hub account yet and I would like one.

**Comment by wayne-optin** [comment]
yeah, I think we're a couple days into the 14 day trial - we should work
out how many we need. My guess is at least 5 right now (Dan, Dave, John,
Mark, Wayne).

I think that each ZenHub seat depends on a github membership in our Organization, too. So if we want ZenHub access for Dan, Dave we need to assign github licenses to them (we have 5 seats bought, 3 assigned so far)
